spring:
  application:
    name: notification-service
  kafka:
    bootstrap-server: localhost:9092
    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeSerializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
            use:
              type:
                headers: false
            value:
              default:
                type: java.util.HashMap

server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: health, info