spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # USER-SERVICE PUBLIC ENDPOINTS
            - id: user-service-public
              order: -1
              uri: http://localhost:8081
              predicates:
                - Path=/api/v1/users/register, /api/v1/users/login
                - Method=POST

            # USER-SERVICE PROTECTED ENDPOINTS
            - id: user-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/v1/users/**
              filters:
                - name: JwtAuthFilter

            # MARKET-DATA-SERVICE
            - id: market-data-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/v1/market/**
              filters:
                - name: JwtAuthFilter

            # WEBSOCKET
            - id: market-websocket
              order: -20
              uri: http://localhost:8082
              predicates:
                - Path=/ws/**
                - Header=Upgrade, (?i)websocket

            # SOCKJS
            - id: market-sockjs
              order: -10
              uri: http://localhost:8082
              predicates:
                - Path=/ws, /ws/**

            # ORDER-SERVICE
            - id: order-service
              uri: http://localhost:8083
              predicates:
                - Path=/api/v1/orders/**
              filters:
                - name: JwtAuthFilter

            # PORTFOLIO-SERVICE
            - id: portfolio-service
              uri: http://localhost:8084
              predicates:
                - Path=/api/v1/portfolio/**
              filters:
                - name: JwtAuthFilter

server:
  port: 8080

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

management:
  endpoints:
    web:
      exposure:
        include: 'health, info'

logging:
  level:
    root: INFO
    org.apache.tomcat: DEBUG
    org.apache.catalina: DEBUG
    org.springframework.web.servlet: TRACE
    org.springframework.cloud.gateway: TRACE
